sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: S8Qw/POIQzKUxH/45tUO6dpUP4Oz5KGezFLtMFyPVup3zH4yTx+YT6gdANs+f0LCOv8Ct5h/Lg1dASh5H4L7whskRn4ZT9OZs3dUTi90h7rCpgu3veuKKFHDeNA+WzmDZehCmoB9T7Eu2d5chEyyK9/YTqdO3pPA6qqIX+uuvl3AqPveGqYI3axHOfig2BuCC9K2Oh+QtnwHJ5L9NY4l2u7EKfC4anauPNxpngUpn00pUT+DLhO4PRuzotaqzZeEsvCI4ROhenPrXwJLntU0MqI//aKtJ0izg2KfGjT9sn9GUDZzhTYDClJzeMRu4sJlzFAgwUXFj/NqnNk6g03ZGH5QqdutKkezCaH/nVJkGgdH3ic2a2+ARadifH3B0/JmV+R2k/Nz08Reb1bSm+CxzCidbcAB/QVGS/qirYr48VfCBNzvifaxbT+GWBKaI/opdbimSapInwotDi+6GT1XORj4WUI3RijUu31EGaftX3OsMzKA/VsaMQ8VV0wYO5VWJ0/7b1TqHLUfZnBMn7M6Zg4DKO9Yt718+JxeWfxNxIekyexABeM1ULcUJQzsEosJwNPhSxgddxRAtuIkLAavnCGOWhLznaA11N4cNlF+ENLj0OFyiBQQ14Nohc/dkDlLHjCNE3BMkac+Yyut5yLEjY8cWAoFOeOww2009N8K3js=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: FloLRa4lwn1SGhgTCGO05xI7Fz4j8vgpcOJGexm7PyYluLYcw4TY2S9PuSVphaAHTJ/b4tWkzSEW2PAEfYTbpeFE8YyBkiFHzxzS/IZ9+RjNATfe8cpj6+Hu9G3kBFHsim7grW8GoZVayBalFOTYqq7qMonbZ1tHbzRxk+foqmq/bbjHSiJxz42H47RXGK0XkCC9UMSP02HOr9fst0UvLQ49/Jc9ulkxgW1XaRw6smETNfwFAycRQV1by0GKIgqdu2EBJOcOgaEQNnFMvn9soW4Xov0fEgAte/Zp1vBs/hjYTeotGrg2LGNhjmT467SqN0TgdV0QeXFZ3omghSGJd8yr4PU0t9fZyryCNM6nQdzzgl0poEeclEq3z59u9RuTvBFM+OhdstT/kqd4f8dFEU7K22Zu1YmfsUzwQLsIx96AX3fEQnXPgna7H+ZkwCOBWcrd1EsuGVVayQcZMYczgvLAGpHM25l/u/4yNL9dkm8zAUAld4KlgIq+YviRyOqKHwr4IwRfezOcbRgziHcY42lJsxTJcxKjP+33QuttSpffTCz14furkWRy2nZSEnb8UjcPHsVETeUNCQkpOwQluLlMQAc6F/MJuP03OXPmeXdbcOCmXnATEbI/oKo+rMzALb/zxtMq02ql6xQr3IFikkmjsEeGVE4d6mgj5rhNh9M=
